using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using SkFabricatorAndErector.Domain.Entities;

namespace SkFabricatorAndErector.Infrastructure.Persistence;

public static class DatabaseExtensions
{
    public static IServiceCollection AddPersistence(this IServiceCollection services, IConfiguration configuration, IWebHostEnvironment environment)
    {
        var provider = configuration.GetValue<string>("DatabaseProvider")?.ToLowerInvariant() ?? "sqlite";

        services.AddDbContext<ApplicationDbContext>(options =>
        {
            options.ConfigureWarnings(w => w.Ignore(Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning));

            var rawConnStr = configuration.GetConnectionString("DefaultConnection") ?? "";
            var isPostgres = provider == "postgres" || provider == "postgresql" || 
                             rawConnStr.StartsWith("postgres", StringComparison.OrdinalIgnoreCase) || 
                             rawConnStr.Contains("neon.tech", StringComparison.OrdinalIgnoreCase);

            if (isPostgres)
            {
                var formattedConnStr = ConvertPostgresConnectionString(rawConnStr);
                options.UseNpgsql(formattedConnStr);
            }
            else
            {
                options.UseSqlite(configuration.GetConnectionString("DefaultConnection") ?? "Data Source=skfabricator.db");
            }
        });

        services.AddIdentity<ApplicationUser, IdentityRole>(options =>
        {
            options.Password.RequiredLength = 8;
            options.Password.RequireDigit = true;
            options.Password.RequireLowercase = true;
            options.Password.RequireUppercase = true;
            options.Password.RequireNonAlphanumeric = true;
        })
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

        return services;
    }

    public static string LastInitLog = "Not initialized yet";

    public static async Task UseDatabaseInitialization(this IApplicationBuilder app, IServiceProvider services, IConfiguration configuration)
    {
        using var scope = services.CreateScope();
        var serviceProvider = scope.ServiceProvider;
        var logger = serviceProvider.GetRequiredService<ILogger<ApplicationDbContext>>();
        var logBuilder = new System.Text.StringBuilder();

        void AppendLog(string msg)
        {
            var line = $"[{DateTime.UtcNow:HH:mm:ss}] {msg}";
            logBuilder.AppendLine(line);
            LastInitLog = logBuilder.ToString();
        }

        AppendLog("Starting database initialization...");

        try
        {
            var context = serviceProvider.GetRequiredService<ApplicationDbContext>();
            AppendLog($"DbContext provider: {context.Database.ProviderName}");

            try
            {
                await context.Database.MigrateAsync();
                AppendLog("EF Core Database Migrations applied successfully.");
            }
            catch (Exception mEx)
            {
                AppendLog($"MigrateAsync warning: {mEx.Message}. Trying EnsureCreatedAsync.");
                try
                {
                    await context.Database.EnsureCreatedAsync();
                    AppendLog("EnsureCreatedAsync completed.");
                }
                catch (Exception ecEx)
                {
                    AppendLog($"EnsureCreatedAsync error: {ecEx.Message}");
                }
            }

            if (context.Database.IsNpgsql())
            {
                try
                {
                    await context.Database.ExecuteSqlRawAsync(@"
                        CREATE TABLE IF NOT EXISTS ""PageImageSlots"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""SlotKey"" text NOT NULL,
                            ""PageName"" text NOT NULL,
                            ""SectionName"" text NOT NULL,
                            ""Label"" text NOT NULL,
                            ""ImageUrl"" text NULL,
                            ""CloudinaryPublicId"" text NULL,
                            ""AltText"" text NULL,
                            ""UpdatedAtUtc"" timestamp with time zone NOT NULL
                        );
                        CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PageImageSlots_SlotKey"" ON ""PageImageSlots"" (""SlotKey"");

                        ALTER TABLE ""AspNetUsers"" ADD COLUMN IF NOT EXISTS ""Role"" text NULL;
                        ALTER TABLE ""AspNetUsers"" ADD COLUMN IF NOT EXISTS ""RefreshToken"" text NULL;
                        ALTER TABLE ""AspNetUsers"" ADD COLUMN IF NOT EXISTS ""RefreshTokenExpiryTime"" timestamp with time zone NOT NULL DEFAULT '0001-01-01 00:00:00+00';
                        ALTER TABLE ""AspNetUsers"" ADD COLUMN IF NOT EXISTS ""PasswordChangeRequired"" boolean NOT NULL DEFAULT false;
                    ");
                    AppendLog("PostgreSQL schema columns and PageImageSlots table verified successfully.");
                }
                catch (Exception sqlEx)
                {
                    AppendLog($"PostgreSQL schema alter warning: {sqlEx.Message}");
                }
            }
            else if (context.Database.IsSqlite())
            {
                try
                {
                    await context.Database.ExecuteSqlRawAsync(@"
                        CREATE TABLE IF NOT EXISTS PageImageSlots (
                            Id INTEGER PRIMARY KEY AUTOINCREMENT,
                            SlotKey TEXT NOT NULL,
                            PageName TEXT NOT NULL,
                            SectionName TEXT NOT NULL,
                            Label TEXT NOT NULL,
                            ImageUrl TEXT NULL,
                            CloudinaryPublicId TEXT NULL,
                            AltText TEXT NULL,
                            UpdatedAtUtc TEXT NOT NULL
                        );
                        CREATE UNIQUE INDEX IF NOT EXISTS IX_PageImageSlots_SlotKey ON PageImageSlots (SlotKey);
                    ");
                }
                catch { }

                try { await context.Database.ExecuteSqlRawAsync("ALTER TABLE AspNetUsers ADD COLUMN Role TEXT NULL;"); } catch { }
                try { await context.Database.ExecuteSqlRawAsync("ALTER TABLE AspNetUsers ADD COLUMN RefreshToken TEXT NULL;"); } catch { }
                try { await context.Database.ExecuteSqlRawAsync("ALTER TABLE AspNetUsers ADD COLUMN RefreshTokenExpiryTime TEXT NOT NULL DEFAULT '0001-01-01 00:00:00';"); } catch { }
                try { await context.Database.ExecuteSqlRawAsync("ALTER TABLE AspNetUsers ADD COLUMN PasswordChangeRequired INTEGER NOT NULL DEFAULT 0;"); } catch { }
                logger.LogInformation("SQLite schema columns and PageImageSlots table verified successfully.");
            }

            await EnsurePageImageSlotsSeededAsync(context);
            await SeedData.InitializeAsync(serviceProvider, configuration);
            logger.LogInformation("Database seeded successfully.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "An error occurred while migrating or seeding the DB.");
        }
    }

    private static async Task EnsurePageImageSlotsSeededAsync(ApplicationDbContext context)
    {
        try
        {
            var defaultSlots = new[]
            {
                new PageImageSlot { SlotKey = "home.hero.background", PageName = "Home", SectionName = "Hero", Label = "Fabrication Yard / Drone Jobsite Shot" },
                new PageImageSlot { SlotKey = "home.whyus.icon.customize-service", PageName = "Home", SectionName = "Why Choose Us", Label = "Customize Service Icon / Photo" },
                new PageImageSlot { SlotKey = "home.whyus.icon.reliable-services", PageName = "Home", SectionName = "Why Choose Us", Label = "Reliable Services Icon / Photo" },
                new PageImageSlot { SlotKey = "home.whyus.icon.client-friendly", PageName = "Home", SectionName = "Why Choose Us", Label = "Client-Friendly Approach Icon / Photo" },
                new PageImageSlot { SlotKey = "home.whyus.icon.competitive-prices", PageName = "Home", SectionName = "Why Choose Us", Label = "Competitive Prices Icon / Photo" },
                new PageImageSlot { SlotKey = "home.whyus.icon.timely-delivery", PageName = "Home", SectionName = "Why Choose Us", Label = "Timely Delivery Icon / Photo" },
                new PageImageSlot { SlotKey = "home.whyus.icon.quality-management", PageName = "Home", SectionName = "Why Choose Us", Label = "Quality Management Icon / Photo" },
                new PageImageSlot { SlotKey = "services.mechanical-piping.card", PageName = "Services", SectionName = "Mechanical & Piping", Label = "Card Thumbnail — Valve/Piping Photo" },
                new PageImageSlot { SlotKey = "services.mechanical-piping.hero", PageName = "Services", SectionName = "Mechanical & Piping", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "services.jacketed-piping.card", PageName = "Services", SectionName = "Jacketed Piping", Label = "Card Thumbnail" },
                new PageImageSlot { SlotKey = "services.jacketed-piping.hero", PageName = "Services", SectionName = "Jacketed Piping", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "services.structure-fabrication.card", PageName = "Services", SectionName = "Structure Fabrication & Erection", Label = "Card Thumbnail" },
                new PageImageSlot { SlotKey = "services.structure-fabrication.hero", PageName = "Services", SectionName = "Structure Fabrication & Erection", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "services.storage-tanks.card", PageName = "Services", SectionName = "Storage Tank Manufacturing", Label = "Card Thumbnail" },
                new PageImageSlot { SlotKey = "services.storage-tanks.hero", PageName = "Services", SectionName = "Storage Tank Manufacturing", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "services.magnetic-filters.card", PageName = "Services", SectionName = "SS Magnetic Filters", Label = "Card Thumbnail" },
                new PageImageSlot { SlotKey = "services.magnetic-filters.hero", PageName = "Services", SectionName = "SS Magnetic Filters", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "services.maintenance.card", PageName = "Services", SectionName = "Plant Maintenance", Label = "Card Thumbnail" },
                new PageImageSlot { SlotKey = "services.maintenance.hero", PageName = "Services", SectionName = "Plant Maintenance", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "services.insulation.card", PageName = "Services", SectionName = "Insulation", Label = "Card Thumbnail" },
                new PageImageSlot { SlotKey = "services.insulation.hero", PageName = "Services", SectionName = "Insulation", Label = "Detail Page Hero" },
                new PageImageSlot { SlotKey = "about.intro.photo", PageName = "About", SectionName = "Introduction", Label = "Supporting Photo Next to Intro Text" },
                new PageImageSlot { SlotKey = "about.safety-triangle.graphic", PageName = "About", SectionName = "Safety", Label = "Service/Quality/Delivery Graphic" },
                new PageImageSlot { SlotKey = "contact.banner.background", PageName = "Contact", SectionName = "Banner", Label = "Contact Page Header Background" },
                new PageImageSlot { SlotKey = "project.proj-1", PageName = "Projects", SectionName = "Piping", Label = "Gas Header Pipeline Assembly" },
                new PageImageSlot { SlotKey = "project.proj-2", PageName = "Projects", SectionName = "Piping", Label = "Water Storage System Piping" },
                new PageImageSlot { SlotKey = "project.proj-3", PageName = "Projects", SectionName = "Maintenance & Ducting", Label = "Industrial Exhaust Ducting Spool" },
                new PageImageSlot { SlotKey = "project.proj-4", PageName = "Projects", SectionName = "Structural", Label = "Factory Ventilation System" },
                new PageImageSlot { SlotKey = "project.proj-5", PageName = "Projects", SectionName = "Piping", Label = "Precision Stainless Spool Piece" },
                new PageImageSlot { SlotKey = "project.proj-6", PageName = "Projects", SectionName = "Maintenance", Label = "Onsite Piping Installation Crew" },
                new PageImageSlot { SlotKey = "project.proj-7", PageName = "Projects", SectionName = "Filters & Vessels", Label = "Exhaust Filter Cyclone Battery" },
                new PageImageSlot { SlotKey = "project.proj-8", PageName = "Projects", SectionName = "Piping", Label = "Skid-Mounted Dosing Skid" },
                new PageImageSlot { SlotKey = "project.proj-9", PageName = "Projects", SectionName = "Filters & Vessels", Label = "SS Magnetic Filter Housing" },
                new PageImageSlot { SlotKey = "project.proj-10", PageName = "Projects", SectionName = "Storage Tanks", Label = "High-Capacity Storage Tank" },
                new PageImageSlot { SlotKey = "project.proj-[#11]", PageName = "Projects", SectionName = "Structural", Label = "Plant Safety Enclosures" },
                new PageImageSlot { SlotKey = "project.proj-11", PageName = "Projects", SectionName = "Structural", Label = "Plant Safety Enclosures" },
                new PageImageSlot { SlotKey = "project.proj-12", PageName = "Projects", SectionName = "Storage Tanks", Label = "Stainless Storage Tank Battery" }
            };

            var existingKeys = await context.PageImageSlots.Select(s => s.SlotKey.ToLower()).ToListAsync();
            var missing = defaultSlots.Where(s => !existingKeys.Contains(s.SlotKey.ToLower())).ToList();
            if (missing.Any())
            {
                context.PageImageSlots.AddRange(missing);
                await context.SaveChangesAsync();
            }
        }
        catch { }
    }

    private static string ConvertPostgresConnectionString(string connString)
    {
        if (string.IsNullOrWhiteSpace(connString)) return connString;
        if (connString.StartsWith("postgres://", StringComparison.OrdinalIgnoreCase) ||
            connString.StartsWith("postgresql://", StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                var uri = new Uri(connString);
                var userInfo = uri.UserInfo.Split(':');
                var username = userInfo.Length > 0 ? Uri.UnescapeDataString(userInfo[0]) : "";
                var password = userInfo.Length > 1 ? Uri.UnescapeDataString(userInfo[1]) : "";
                var database = uri.AbsolutePath.TrimStart('/');
                var host = uri.Host;
                var port = uri.Port > 0 ? uri.Port : 5432;

                return $"Host={host};Port={port};Database={database};Username={username};Password={password};SSL Mode=Require;Trust Server Certificate=true";
            }
            catch
            {
                return connString;
            }
        }
        return connString;
    }
}
